const [brandsData,fairsData,storesData]=await Promise.all([
  fetch('./data/brands.json').then(r=>r.json()),
  fetch('./data/fairs.json').then(r=>r.json()),
  fetch('./data/stores.json').then(r=>r.json()).catch(()=>({stores:[]}))
]);

const DAY=86400000;
const AREA_ORDER=['toyohashi','toyokawa','gamagori','okazaki','hamamatsu'];
const AREA_LABEL={toyohashi:'豊橋',toyokawa:'豊川',gamagori:'蒲郡',okazaki:'岡崎',hamamatsu:'浜松'};
const CAT_LABEL={yakiniku:'焼肉',shabu:'しゃぶしゃぶ',buffet:'ビュッフェ',steak:'ステーキ'};
let tab='active',brandFilter=null;

function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function status(c){if(['ended_official','ended_by_date','stale_unverified'].includes(c.lifecycleStatus))return'ended';const now=new Date(),today=new Date(now.toLocaleString('en-US',{timeZone:'Asia/Tokyo'}));today.setHours(0,0,0,0);const s=c.startDate?new Date(c.startDate+'T00:00:00+09:00'):null,e=c.endDate?new Date(c.endDate+'T23:59:59+09:00'):null;if(s&&s>today)return'upcoming';if(e&&e<today)return'ended';return'active'}
function isNew(c){const f=c.firstSeenAt?new Date(c.firstSeenAt):null;if(!f)return false;const age=(Date.now()-f)/DAY;return age>=0&&age<=7}
function ending(c){if(status(c)!=='active'||!c.endDate)return false;const e=new Date(c.endDate+'T23:59:59+09:00');const left=(e-Date.now())/DAY;return left>=0&&left<=7}
function matchesTab(c){if(tab==='new')return isNew(c)&&status(c)!=='ended';if(tab==='ending')return ending(c);return status(c)===tab}
function important(c){return c.priority==='P1'||c.priority==='P2'}
function countFor(id,t){return fairsData.campaigns.filter(c=>c.brandId===id&&important(c)&&(t==='new'?isNew(c)&&status(c)!=='ended':t==='ending'?ending(c):status(c)===t)).length}
function sortCampaigns(rows){return [...rows].sort((a,b)=>{const p=(a.priority==='P1'?0:1)-(b.priority==='P1'?0:1);if(p)return p;const da=a.startDate||'9999-99-99',db=b.startDate||'9999-99-99';return da.localeCompare(db)})}

function renderBrands(){const g=document.querySelector('#brand-grid');g.innerHTML='';for(const b of [...brandsData.brands].sort((a,b)=>a.order-b.order)){const a=countFor(b.id,'active'),n=countFor(b.id,'new'),e=countFor(b.id,'ending');g.insertAdjacentHTML('beforeend',`<button class="brand ${brandFilter===b.id?'selected':''}" data-brand="${esc(b.id)}"><b>${esc(b.name)}</b><span class="meta">開催中 ${a}件${n?` ・ 新着 ${n}`:''}${e?` ・ 終了間近 ${e}`:''}</span></button>`)}document.querySelectorAll('.brand').forEach(el=>el.onclick=()=>{brandFilter=brandFilter===el.dataset.brand?null:el.dataset.brand;renderBrands();renderList();document.querySelector('#list-title')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function fmtDate(c){if(!c.startDate&&!c.endDate)return c.endDateText?`終了：${c.endDateText}`:'期間：公式記載を確認中';if(c.startDate&&c.endDate)return`${c.startDate} ～ ${c.endDate}`;if(c.startDate)return`${c.startDate} ～${c.endDateText?`（${c.endDateText}）`:''}`;return`～ ${c.endDate}`}
function storeState(c,s){const override=(s.campaignOverrides||[]).find(o=>c.title.includes(o.match));if(override)return override.available?'yes':'no';if((c.targetStores||[]).includes(s.id))return'yes';if((c.targetAreas||[]).includes(s.area))return'yes';if(c.regionScope==='national')return'yes';if(c.regionScope==='aichi'&&['toyohashi','toyokawa','gamagori','okazaki'].includes(s.area))return'yes';if(c.regionScope==='shizuoka'&&s.area==='hamamatsu')return'yes';return'unknown'}
function brandAvailability(brandId,rows){const stores=(storesData.stores||[]).filter(s=>s.brandId===brandId);if(!stores.length)return'';const chips=[];for(const area of AREA_ORDER){const ss=stores.filter(s=>s.area===area);if(!ss.length)continue;const states=[];for(const c of rows)for(const s of ss)states.push(storeState(c,s));const symbol=states.includes('yes')?'○':states.length&&states.every(x=>x==='no')?'×':'△';chips.push(`<span class="area-chip ${symbol==='○'?'yes':symbol==='×'?'no':'unknown'}">${AREA_LABEL[area]} ${symbol}</span>`)}return chips.length?`<div class="brand-availability"><span class="section-label">近隣エリア</span><div class="area-chips">${chips.join('')}</div><small>○ 対象確認済み　△ 対象要確認　× 対象外確認済み</small></div>`:''}
function tagsFor(c){return[c.allYouCanEat?'食べ放題':null,...(c.limitedIngredients||[]).slice(0,4)].filter(Boolean)}
function campaignRow(c){const tags=tagsFor(c);return`<div class="fair-row"><div class="fair-row-main"><div class="fair-row-title"><a href="${esc(c.officialUrl)}" target="_blank" rel="noopener">${esc(c.title)}</a><span class="priority ${c.priority==='P1'?'p1':'p2'}">${esc(c.priority||'')}</span></div><div class="fair-row-meta"><span>${esc(fmtDate(c))}</span>${c.priceText?`<strong>${esc(c.priceText)}</strong>`:''}</div>${(c.targetCourses||[]).length?`<div class="courses">対象コース：${esc(c.targetCourses.join(' / '))}</div>`:''}${tags.length?`<div class="tags">${tags.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}</div></div>`}
function gallery(rows,brand){const seen=new Set(),images=[];for(const c of rows){if(c.imageUrl&&!seen.has(c.imageUrl)){seen.add(c.imageUrl);images.push({url:c.imageUrl,title:c.title,href:c.officialUrl})}if(images.length===4)break}if(!images.length)return`<div class="gallery gallery-empty"><div>${esc(brand.name)}</div><small>公式画像を確認中</small></div>`;return`<div class="gallery gallery-${images.length}">${images.map((x,i)=>`<a class="gallery-item ${i===0?'main':''}" href="${esc(x.href)}" target="_blank" rel="noopener" aria-label="${esc(x.title)}"><img src="${esc(x.url)}" alt="${esc(x.title)}" loading="lazy" onerror="this.closest('a').remove()"></a>`).join('')}</div>`}
function brandCard(brand,rows){const sorted=sortCampaigns(rows);const activeCount=sorted.filter(c=>status(c)==='active').length;const upcomingCount=sorted.filter(c=>status(c)==='upcoming').length;const summary=[activeCount?`開催中 ${activeCount}件`:null,upcomingCount?`近日開始 ${upcomingCount}件`:null].filter(Boolean).join(' ・ ')||`${sorted.length}件`;const official=brand.homeUrl||sorted[0]?.sourceUrl||sorted[0]?.officialUrl||'#';return`<article class="restaurant-card" id="brand-${esc(brand.id)}"><div class="restaurant-head"><div><div class="category">${esc(CAT_LABEL[brand.category]||'レストラン')}</div><h3>${esc(brand.name)}</h3><div class="restaurant-summary">${esc(summary)}</div></div><span class="brand-rank">${String(brand.order).padStart(2,'0')}</span></div>${gallery(sorted,brand)}<div class="restaurant-body"><div class="section-title"><span>開催フェア</span><small>${sorted.length}件</small></div><div class="fair-list">${sorted.map(campaignRow).join('')}</div>${brandAvailability(brand.id,sorted)}<a class="brand-official" href="${esc(official)}" target="_blank" rel="noopener">${esc(brand.name)} 公式サイトへ <span>↗</span></a></div></article>`}
function renderList(){const labels={active:'開催中',new:'新着',upcoming:'近日開始',ending:'終了間近'};const suffix=brandFilter?` ・ ${brandsData.brands.find(b=>b.id===brandFilter)?.name||''}`:'';document.querySelector('#list-title').textContent=labels[tab]+suffix;const rows=fairsData.campaigns.filter(c=>important(c)&&matchesTab(c));const brands=[...brandsData.brands].sort((a,b)=>a.order-b.order).filter(b=>(!brandFilter||b.id===brandFilter)&&rows.some(c=>c.brandId===b.id));document.querySelector('#campaign-list').innerHTML=brands.length?brands.map(b=>brandCard(b,rows.filter(c=>c.brandId===b.id))).join(''):`<div class="empty">現在表示できるフェアはありません。</div>`}
document.querySelectorAll('#status-tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('#status-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderList()});
renderBrands();renderList();
