const [brandsData,fairsData]=await Promise.all([fetch('./data/brands.json').then(r=>r.json()),fetch('./data/fairs.json').then(r=>r.json())]);
const DAY=86400000;let tab='active',brandFilter=null;
function status(c){if(c.lifecycleStatus==='ended_official'||c.lifecycleStatus==='ended_by_date'||c.lifecycleStatus==='stale_unverified')return'ended';const now=new Date(),today=new Date(now.toLocaleString('en-US',{timeZone:'Asia/Tokyo'}));today.setHours(0,0,0,0);const s=c.startDate?new Date(c.startDate+'T00:00:00+09:00'):null,e=c.endDate?new Date(c.endDate+'T23:59:59+09:00'):null;if(s&&s>today)return'upcoming';if(e&&e<today)return'ended';return'active'}
function isNew(c){const f=c.firstSeenAt?new Date(c.firstSeenAt):null;return!!f&&(Date.now()-f)/DAY<=7}
function ending(c){if(status(c)!=='active'||!c.endDate)return false;const e=new Date(c.endDate+'T23:59:59+09:00');return(e-Date.now())/DAY<=7&&(e-Date.now())>=0}
function matchesTab(c){if(tab==='new')return isNew(c)&&status(c)!=='ended';if(tab==='ending')return ending(c);return status(c)===tab}
function important(c){return c.priority==='P1'||c.priority==='P2'}
function countFor(id,t){return fairsData.campaigns.filter(c=>c.brandId===id&&important(c)&&(t==='new'?isNew(c)&&status(c)!=='ended':t==='ending'?ending(c):status(c)===t)).length}
function renderBrands(){const g=document.querySelector('#brand-grid');g.innerHTML='';for(const b of [...brandsData.brands].sort((a,b)=>a.order-b.order)){const a=countFor(b.id,'active'),n=countFor(b.id,'new'),e=countFor(b.id,'ending');g.insertAdjacentHTML('beforeend',`<button class="brand ${brandFilter===b.id?'selected':''}" data-brand="${b.id}"><b>${b.name}</b><span class="meta">開催中 ${a}件${n?` ・ 新着 ${n}件`:''}${e?` ・ ⚠終了間近 ${e}件`:''}</span></button>`)}document.querySelectorAll('.brand').forEach(el=>el.onclick=()=>{brandFilter=brandFilter===el.dataset.brand?null:el.dataset.brand;renderBrands();renderList()})}
function fmtDate(c){if(!c.startDate&&!c.endDate)return c.endDateText?`終了：${c.endDateText}`:'期間：公式記載を確認中';if(c.startDate&&c.endDate)return`${c.startDate} ～ ${c.endDate}`;if(c.startDate)return`${c.startDate} ～${c.endDateText?`（${c.endDateText}）`:''}`;return`～ ${c.endDate}`}
function card(c){const tags=[c.allYouCanEat?'食べ放題':null,...(c.limitedIngredients||[]).slice(0,4)].filter(Boolean);const courses=(c.targetCourses||[]).length?`<div class="courses">対象コース：${c.targetCourses.join(' / ')}</div>`:'';const image=c.imageUrl?`<img class="campaign-img" src="${c.imageUrl}" alt="" loading="lazy" onerror="this.remove()">`:'';return`<article class="campaign">${image}<div class="campaign-top"><div><b>${c.title}</b><div class="meta">${c.brandName||c.brandId}</div></div><span class="priority">${c.priority||''}</span></div><div class="period">${fmtDate(c)}</div>${c.priceText?`<div class="price">${c.priceText}</div>`:''}${courses}${tags.length?`<div class="tags">${tags.map(x=>`<span>${x}</span>`).join('')}</div>`:''}<a class="official" href="${c.officialUrl}" target="_blank" rel="noopener">公式情報を見る</a></article>`}
function renderList(){const labels={active:'開催中',new:'新着',upcoming:'近日開始',ending:'終了間近'};const suffix=brandFilter?` ・ ${brandsData.brands.find(b=>b.id===brandFilter)?.name||''}`:'';document.querySelector('#list-title').textContent=labels[tab]+suffix;const rows=fairsData.campaigns.filter(c=>matchesTab(c)&&(!brandFilter?important(c):c.brandId===brandFilter&&c.priority!=='P4'));document.querySelector('#campaign-list').innerHTML=rows.length?rows.map(card).join(''):`<div class="empty">現在表示できるフェアはありません。</div>`}
document.querySelectorAll('#status-tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('#status-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderList()});renderBrands();renderList();