import crypto from 'node:crypto';
import { INCLUDE_KEYWORDS, EXCLUDE_KEYWORDS } from './source-registry.mjs';

const GENERIC=new Set(['食べ放題','食べ放題一覧','海鮮','デザート','ドリンク・飲み放題メニュー','ランチ食べ放題コース','牛タン・上焼肉コース','黒毛和牛コース','黒毛和牛','キャンペーン','期間限定メニュー']);
const INGREDIENTS=['牛タン','牛たん','黒毛和牛','鴨肉','きのこ','九州黒豚','松茸','サーモン','秋刀魚','蟹','かに','カニ','海鮮','メロン','苺','いちご','韓国','台湾','北海道','蜜芋','秋栗','和梨'];
const SOCIAL=/フォロー.{0,3}リポスト|SNSキャンペーン|プレゼントキャンペーン/;
const FOOD_TERMS=['カルビ','牛タン','牛たん','焼肉','肉','鴨','豚','黒毛和牛','サーモン','寿司','秋刀魚','松茸','きのこ','つみれ','海鮮','蟹','かに','カニ','しゃぶ','鍋','キムチ','ラーメン','ステーキ','デザート','プリン','シャーベット','ロコモコ','チーズ','ポテト'];
const BAD_IMAGE_RE=/(?:logo|ロゴ|icon|favicon|sprite|loading|placeholder|header|footer|sns|share|common\/og|img_ogp|\/ogp(?:[._-]|\.)|appstore|googleplay)/i;

export function textFromHtml(s=''){return s.replace(/<img\b[^>]*alt=["']([^"']*)["'][^>]*>/gi,' $1 ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
export function absolute(base,href){try{return new URL(href,base).href}catch{return null}}
export function canonicalUrl(url){try{const u=new URL(url);u.hash='';u.searchParams.delete('utm_source');u.searchParams.delete('utm_medium');u.searchParams.delete('utm_campaign');u.pathname=u.pathname.replace(/\/index\.html$/,'/');return u.href}catch{return url}}
export function titleFromHtml(html){const h=html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);if(h){const t=textFromHtml(h[1]);if(t)return t}const m=html.match(/<meta[^>]+(?:property|name)=["']og:title["'][^>]+content=["']([^"']+)["']/i)||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?textFromHtml(m[1]):null}
export function linksFromHtml(html,base){const out=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const title=textFromHtml(m[2]);const raw=absolute(base,m[1]);const url=raw?canonicalUrl(raw):null;if(url)out.push({title,url})}return out}
export function rawDetailUrls(brandId,html,base){const patterns=brandId==='gyukaku'?[/news\.php\?id=[A-Za-z0-9_\-]+/g,/news\/news\.php\?id=[A-Za-z0-9_\-]+/g,/\/lp\/[A-Za-z0-9_\-\/]+/g]:brandId==='yakiniku-king'?[/\/news\/\d+\//g,/\/menu_all\/season\/[A-Za-z0-9_\-]+\//g]:brandId==='yuzuan'?[/\/news\/\d+\//g,/\/seasonal\//g]:brandId==='syabuyo'?[/\/syabuyo\/menu\/fair[^"'<> ]*/g,/\/syabuyo\/campaign\/[^"'<> ]*/g]:[];const found=[];for(const re of patterns){for(const m of html.matchAll(re)){const url=canonicalUrl(absolute(base,m[0]));if(url)found.push({title:'',url})}}return found}
export function relevantTitle(title=''){if(!title||GENERIC.has(title)||SOCIAL.test(title)||EXCLUDE_KEYWORDS.some(k=>title.includes(k)))return false;return INCLUDE_KEYWORDS.some(k=>title.includes(k))}
export function allowedPath(brandId,url){const p=new URL(url).pathname;if(brandId==='yakiniku-king')return /^\/news\/\d+\/?$/.test(p)||(p.startsWith('/menu_all/season/')&&p!=='/menu_all/season/'&&!p.includes('/page/'));if(brandId==='gyukaku')return (p.startsWith('/news/')&&p!=='/news/')||p.startsWith('/lp/');if(brandId==='syabuyo')return p.includes('/syabuyo/menu/fair')||p.includes('/syabuyo/campaign/');if(brandId==='yuzuan')return /^\/news\/\d+\/?$/.test(p)||p.startsWith('/seasonal/');return false}
export function campaignId(brandId,url){return crypto.createHash('sha1').update(`${brandId}|${canonicalUrl(url)}`).digest('hex').slice(0,16)}
function iso(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
export function firstDate(text){const m=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日/);return m?iso(m[1],m[2],m[3]):null}
export function dateFields(text){let r=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日[^\d]{0,20}[〜～~\-][^\d]{0,20}(?:(20\d{2})年)?\s*(\d{1,2})月\s*(\d{1,2})日/);if(r)return{startDate:iso(r[1],r[2],r[3]),endDate:iso(r[4]||r[1],r[5],r[6]),endDateText:null};r=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日[^\d]{0,20}[〜～~\-][^\d]{0,20}(\d{1,2})日/);if(r)return{startDate:iso(r[1],r[2],r[3]),endDate:iso(r[1],r[2],r[4]),endDateText:null};const s=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日.{0,10}?(?:より|から|販売開始|発売開始|開始)/);return{startDate:s?iso(s[1],s[2],s[3]):null,endDate:null,endDateText:/なくなり次第終了|無くなり次第終了/.test(text)?'なくなり次第終了':null}}

function attr(tag,name){const m=tag.match(new RegExp(`\\b${name}\\s*=\\s*["']([^"']+)["']`,'i'));return m?m[1]:null}
function srcFromTag(tag){for(const n of ['data-src','data-lazy-src','data-original','src']){const v=attr(tag,n);if(v&&!/^data:/i.test(v))return v}const ss=attr(tag,'srcset');if(ss){const parts=ss.split(',').map(x=>x.trim().split(/\s+/)[0]).filter(Boolean);if(parts.length)return parts.at(-1)}return null}
function dimension(tag,name){const v=attr(tag,name);const n=v?Number(String(v).replace(/[^0-9.]/g,'')):0;return Number.isFinite(n)?n:0}
function themeTerms(title=''){const known=['韓国','ハワイ','北海道','沖縄','秋','春','夏','冬','牛タン','牛たん','鴨','きのこ','松茸','サーモン','秋刀魚'];return known.filter(x=>title.includes(x))}
function scoreImage({url,tag,context,title,isOg=false}){const alt=[attr(tag,'alt'),attr(tag,'title'),attr(tag,'class'),attr(tag,'id')].filter(Boolean).join(' ');const hay=`${url} ${alt} ${context}`;let score=0;const foods=FOOD_TERMS.filter(x=>hay.includes(x));const themes=themeTerms(title).filter(x=>hay.includes(x));if(foods.length)score+=Math.min(10,6+foods.length);if(themes.length)score+=Math.min(6,2+themes.length);if(/(?:fair|season|menu|product|item|dish|food|main|hero|visual|mv|kv)/i.test(url))score+=2;if(/\/uploads\/2026\//.test(url))score+=2;const w=dimension(tag,'width'),h=dimension(tag,'height');if(w>=700||h>=500)score+=3;else if(w>=400||h>=300)score+=2;if(alt&&alt.length>=3&&alt.length<=120)score+=1;if(BAD_IMAGE_RE.test(`${url} ${alt}`))score-=12;if(/(?:店舗|スタッフ|求人|採用|地図|外観|内観)/.test(alt))score-=8;if((w&&w<250)||(h&&h<140))score-=4;if(!foods.length&&!themes.length)score-=3;if(isOg)score-=2;return score}
export function imageFromHtml(html,base,{title=''}={}){const candidates=[];const re=/<img\b[^>]*>/gi;let m;while((m=re.exec(html))){const raw=srcFromTag(m[0]);if(!raw)continue;const url=absolute(base,raw);if(!url||/\.(?:svg|gif)(?:\?|$)/i.test(url))continue;const context=textFromHtml(html.slice(Math.max(0,m.index-350),Math.min(html.length,m.index+m[0].length+550)));candidates.push({url,tag:m[0],context,score:scoreImage({url,tag:m[0],context,title})})}const og=html.match(/<meta[^>]+(?:property|name)=["']og:image["'][^>]+content=["']([^"']+)["']/i)||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']og:image["']/i);if(og){const url=absolute(base,og[1]);if(url)candidates.push({url,tag:'',context:'',score:scoreImage({url,tag:'',context:'',title,isOg:true})})}candidates.sort((a,b)=>b.score-a.score);const best=candidates[0];return best&&best.score>=4?best.url:null}

export function lifecycleFields({text,startDate,endDate,publishedDate,campaignType,now=new Date()}){if(/販売終了いたしました|販売を終了しました|キャンペーンは終了しました/.test(text))return{lifecycleStatus:'ended_official',staleAfterDays:null};if(endDate&&new Date(`${endDate}T23:59:59+09:00`)<now)return{lifecycleStatus:'ended_by_date',staleAfterDays:null};const staleAfterDays=campaignType==='price_change'?30:campaignType==='other'?30:60;const anchor=startDate||publishedDate;if(anchor&&!endDate){const age=(now-new Date(`${anchor}T00:00:00+09:00`))/86400000;if(age>staleAfterDays)return{lifecycleStatus:'stale_unverified',staleAfterDays}}return{lifecycleStatus:'current',staleAfterDays}}
export function targetCoursesFromText(brandId,text){const out=[];if(brandId==='yakiniku-king'){if(text.includes('きんぐコース'))out.push('きんぐコース');if(text.includes('プレミアムコース'))out.push('プレミアムコース')}if(brandId==='gyukaku'){for(const n of ['50品コース','70品コース','牛角コース','牛タンコース','牛タン・上焼肉コース','黒毛和牛コース'])if(text.includes(n))out.push(n)}if(brandId==='yuzuan'&&text.includes('季節のゆず庵コース'))out.push('季節のゆず庵コース');return [...new Set(out)]}
function priceFields(title,text){let m=text.match(/食べ放題[^。]{0,120}?通常[^。]{0,50}?税込\s*([0-9,]+)円/);if(m){const off=text.match(/([0-9,]+)円引き/);return{price:Number(m[1].replace(/,/g,'')),priceText:`食べ放題 通常税込${m[1]}円${off?`から${off[1]}円引き`:''}`}}m=title.match(/([0-9,]+)円/);if(m)return{price:Number(m[1].replace(/,/g,'')),priceText:`${m[1]}円`};m=text.match(/クーポン利用価格\s*([0-9,]+)円\s*\(税込([0-9,]+)円\)/);if(m)return{price:Number(m[2].replace(/,/g,'')),priceText:`クーポン税込${m[2]}円`};return{price:null,priceText:null}}
export function deriveFields(title,text){let campaignType='other',priority='P3';if(/フェア|期間限定|季節/.test(title)){campaignType='fair';priority='P1'}if(/食べ放題/.test(title)){campaignType='all_you_can_eat';priority='P1'}if(/コラボ/.test(title)){campaignType='collaboration';priority='P1'}if(/半額|\d+%OFF|特別価格|値引/.test(title)){campaignType='discount';priority='P2'}if(/価格改定/.test(title)){campaignType='price_change';priority='P2'}const p=priceFields(title,text);const regionScope=/東海3県|東海三県/.test(text)?'tokai':/愛知県限定|愛知限定/.test(text)?'aichi':/静岡県限定|静岡限定/.test(text)?'shizuoka':/店舗限定/.test(title)?'store_limited':/全国/.test(title)?'national':'unknown';return{campaignType,priority,price:p.price,priceText:p.priceText,allYouCanEat:/食べ放題/.test(title)||/食べ放題/.test(text),regionScope,limitedIngredients:INGREDIENTS.filter(x=>text.includes(x)).slice(0,8),weekdayCondition:/平日限定/.test(title)||/平日のみ/.test(text)?'平日限定':null}}
