import crypto from 'node:crypto';
import { INCLUDE_KEYWORDS, EXCLUDE_KEYWORDS } from './source-registry.mjs';

const GENERIC=new Set(['食べ放題','食べ放題一覧','海鮮','デザート','ドリンク・飲み放題メニュー','ランチ食べ放題コース','牛タン・上焼肉コース','黒毛和牛コース','黒毛和牛','キャンペーン']);
const INGREDIENTS=['牛タン','牛たん','黒毛和牛','鴨肉','きのこ','九州黒豚','松茸','サーモン','秋刀魚','蟹','かに','カニ','海鮮','メロン','苺','いちご','韓国','台湾','北海道','蜜芋','秋栗','和梨'];

export function textFromHtml(s=''){return s.replace(/<img\b[^>]*alt=["']([^"']*)["'][^>]*>/gi,' $1 ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
export function absolute(base,href){try{return new URL(href,base).href}catch{return null}}
export function linksFromHtml(html,base){const out=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const title=textFromHtml(m[2]);const url=absolute(base,m[1]);if(title&&url)out.push({title,url})}return out}
export function relevantTitle(title){if(GENERIC.has(title)||EXCLUDE_KEYWORDS.some(k=>title.includes(k)))return false;return INCLUDE_KEYWORDS.some(k=>title.includes(k))}
export function allowedPath(brandId,url){const p=new URL(url).pathname;if(brandId==='yakiniku-king')return /^\/news\/\d+\/?$/.test(p)||p.startsWith('/menu_all/season/');if(brandId==='gyukaku')return p.startsWith('/news/')&&p!=='/news/';if(brandId==='syabuyo')return p.includes('/syabuyo/menu/fair')||p.includes('/syabuyo/campaign/');if(brandId==='yuzuan')return /^\/news\/\d+\/?$/.test(p)||p.startsWith('/seasonal/');return false}
export function campaignId(brandId,url){return crypto.createHash('sha1').update(`${brandId}|${url}`).digest('hex').slice(0,16)}
function iso(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
export function dateFields(text){const r=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日[^\d]{0,16}[〜～~\-][^\d]{0,16}(?:(20\d{2})年)?\s*(\d{1,2})月\s*(\d{1,2})日/);if(r)return{startDate:iso(r[1],r[2],r[3]),endDate:iso(r[4]||r[1],r[5],r[6]),endDateText:null};const s=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日(?:より|から|開始|販売開始|発売)/);return{startDate:s?iso(s[1],s[2],s[3]):null,endDate:null,endDateText:/なくなり次第終了|無くなり次第終了/.test(text)?'なくなり次第終了':null}}
export function imageFromHtml(html,base){const m=html.match(/<meta[^>]+(?:property|name)=["']og:image["'][^>]+content=["']([^"']+)["']/i)||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']og:image["']/i);return m?absolute(base,m[1]):null}
export function deriveFields(title,text){let campaignType='other',priority='P3';const both=`${title} ${text}`;if(/フェア|期間限定|季節/.test(both)){campaignType='fair';priority='P1'}if(/食べ放題/.test(both)){campaignType='all_you_can_eat';priority='P1'}if(/コラボ/.test(both)){campaignType='collaboration';priority='P1'}if(/半額|\d+%OFF|特別価格|値引/.test(both)){campaignType='discount';priority='P2'}if(/価格改定/.test(both)){campaignType='price_change';priority='P2'}const pm=text.match(/(?:コース|食べ放題)[^。]{0,80}?税込\s*([0-9,]+)円/);const regionScope=/東海3県|東海三県/.test(text)?'tokai':/愛知県限定|愛知限定/.test(text)?'aichi':/静岡県限定|静岡限定/.test(text)?'shizuoka':/店舗限定|一部店舗/.test(text)?'store_limited':/全国/.test(text)?'national':'unknown';return{campaignType,priority,price:pm?Number(pm[1].replace(/,/g,'')):null,priceText:pm?`税込${pm[1]}円`:null,allYouCanEat:/食べ放題/.test(text),regionScope,limitedIngredients:INGREDIENTS.filter(x=>text.includes(x)).slice(0,8),weekdayCondition:/平日限定/.test(text)?'平日限定':null}}
