import crypto from 'node:crypto';
import { INCLUDE_KEYWORDS, EXCLUDE_KEYWORDS } from './source-registry.mjs';

const GENERIC=new Set(['食べ放題','食べ放題一覧','海鮮','デザート','ドリンク・飲み放題メニュー','ランチ食べ放題コース','牛タン・上焼肉コース','黒毛和牛コース','黒毛和牛','キャンペーン','期間限定メニュー']);
const INGREDIENTS=['牛タン','牛たん','黒毛和牛','鴨肉','きのこ','九州黒豚','松茸','サーモン','秋刀魚','蟹','かに','カニ','海鮮','メロン','苺','いちご','韓国','台湾','北海道','蜜芋','秋栗','和梨'];
const SOCIAL=/フォロー.{0,3}リポスト|SNSキャンペーン|プレゼントキャンペーン/;

export function textFromHtml(s=''){return s.replace(/<img\b[^>]*alt=["']([^"']*)["'][^>]*>/gi,' $1 ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
export function absolute(base,href){try{return new URL(href,base).href}catch{return null}}
export function canonicalUrl(url){try{const u=new URL(url);u.hash='';u.searchParams.delete('utm_source');u.searchParams.delete('utm_medium');u.searchParams.delete('utm_campaign');u.pathname=u.pathname.replace(/\/index\.html$/,'/');return u.href}catch{return url}}
export function titleFromHtml(html){const h=html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);if(h){const t=textFromHtml(h[1]);if(t)return t}const m=html.match(/<meta[^>]+(?:property|name)=["']og:title["'][^>]+content=["']([^"']+)["']/i)||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?textFromHtml(m[1]):null}
export function linksFromHtml(html,base){const out=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const title=textFromHtml(m[2]);const raw=absolute(base,m[1]);const url=raw?canonicalUrl(raw):null;if(url)out.push({title,url})}return out}
export function rawDetailUrls(brandId,html,base){const patterns=brandId==='gyukaku'?[/news\.php\?id=[A-Za-z0-9_\-]+/g,/news\/news\.php\?id=[A-Za-z0-9_\-]+/g,/\/lp\/[A-Za-z0-9_\-\/]+/g]:brandId==='yakiniku-king'?[/\/news\/\d+\//g,/\/menu_all\/season\/[A-Za-z0-9_\-]+\//g]:brandId==='yuzuan'?[/\/news\/\d+\//g,/\/seasonal\//g]:brandId==='syabuyo'?[/\/syabuyo\/menu\/fair[^"'<> ]*/g,/\/syabuyo\/campaign\/[^"'<> ]*/g]:[];const found=[];for(const re of patterns){for(const m of html.matchAll(re)){const url=canonicalUrl(absolute(base,m[0]));if(url)found.push({title:'',url})}}return found}
export function relevantTitle(title=''){if(!title||GENERIC.has(title)||SOCIAL.test(title)||EXCLUDE_KEYWORDS.some(k=>title.includes(k)))return false;return INCLUDE_KEYWORDS.some(k=>title.includes(k))}
export function allowedPath(brandId,url){const p=new URL(url).pathname;if(brandId==='yakiniku-king')return /^\/news\/\d+\/?$/.test(p)||(p.startsWith('/menu_all/season/')&&p!=='/menu_all/season/'&&!p.includes('/page/'));if(brandId==='gyukaku')return (p.startsWith('/news/')&&p!=='/news/')||p.startsWith('/lp/');if(brandId==='syabuyo')return p.includes('/syabuyo/menu/fair')||p.includes('/syabuyo/campaign/');if(brandId==='yuzuan')return /^\/news\/\d+\/?$/.test(p)||p.startsWith('/seasonal/');return false}
export function campaignId(brandId,url){return crypto.createHash('sha1').update(`${brandId}|${canonicalUrl(url)}`).digest('hex').slice(0,16)}
function iso(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
export function firstDate(text){const m=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日/);return m?iso(m[1],m[2],m[3]):null}
export function dateFields(text){let r=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日[^\d]{0,20}[〜～~\-][^\d]{0,20}(?:(20\d{2})年)?\s*(\d{1,2})月\s*(\d{1,2})日/);if(r)return{startDate:iso(r[1],r[2],r[3]),endDate:iso(r[4]||r[1],r[5],r[6]),endDateText:null};r=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日[^\d]{0,20}[〜～~\-][^\d]{0,20}(\d{1,2})日/);if(r)return{startDate:iso(r[1],r[2],r[3]),endDate:iso(r[1],r[2],r[4]),endDateText:null};const s=text.match(/(20\d{2})年\s*(\d{1,2})月\s*(\d{1,2})日.{0,10}?(?:より|から|販売開始|発売開始|開始)/);return{startDate:s?iso(s[1],s[2],s[3]):null,endDate:null,endDateText:/なくなり次第終了|無くなり次第終了/.test(text)?'なくなり次第終了':null}}
export function imageFromHtml(html,base){const m=html.match(/<meta[^>]+(?:property|name)=["']og:image["'][^>]+content=["']([^"']+)["']/i)||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']og:image["']/i);return m?absolute(base,m[1]):null}
export function lifecycleFields({text,startDate,endDate,publishedDate,campaignType,now=new Date()}){if(/販売終了いたしました|販売を終了しました|キャンペーンは終了しました/.test(text))return{lifecycleStatus:'ended_official',staleAfterDays:null};if(endDate&&new Date(`${endDate}T23:59:59+09:00`)<now)return{lifecycleStatus:'ended_by_date',staleAfterDays:null};const staleAfterDays=campaignType==='price_change'?30:campaignType==='other'?30:60;const anchor=startDate||publishedDate;if(anchor&&!endDate){const age=(now-new Date(`${anchor}T00:00:00+09:00`))/86400000;if(age>staleAfterDays)return{lifecycleStatus:'stale_unverified',staleAfterDays}}return{lifecycleStatus:'current',staleAfterDays}}
export function targetCoursesFromText(brandId,text){const out=[];if(brandId==='yakiniku-king'){if(text.includes('きんぐコース'))out.push('きんぐコース');if(text.includes('プレミアムコース'))out.push('プレミアムコース')}if(brandId==='gyukaku'){for(const n of ['50品コース','70品コース','牛角コース','牛タンコース','牛タン・上焼肉コース','黒毛和牛コース'])if(text.includes(n))out.push(n)}if(brandId==='yuzuan'&&text.includes('季節のゆず庵コース'))out.push('季節のゆず庵コース');return [...new Set(out)]}
function priceFields(title,text){let m=text.match(/食べ放題[^。]{0,120}?通常[^。]{0,50}?税込\s*([0-9,]+)円/);if(m){const off=text.match(/([0-9,]+)円引き/);return{price:Number(m[1].replace(/,/g,'')),priceText:`食べ放題 通常税込${m[1]}円${off?`から${off[1]}円引き`:''}`}}m=title.match(/([0-9,]+)円/);if(m)return{price:Number(m[1].replace(/,/g,'')),priceText:`${m[1]}円`};m=text.match(/クーポン利用価格\s*([0-9,]+)円\s*\(税込([0-9,]+)円\)/);if(m)return{price:Number(m[2].replace(/,/g,'')),priceText:`クーポン税込${m[2]}円`};return{price:null,priceText:null}}
export function deriveFields(title,text){let campaignType='other',priority='P3';if(/フェア|期間限定|季節/.test(title)){campaignType='fair';priority='P1'}if(/食べ放題/.test(title)){campaignType='all_you_can_eat';priority='P1'}if(/コラボ/.test(title)){campaignType='collaboration';priority='P1'}if(/半額|\d+%OFF|特別価格|値引/.test(title)){campaignType='discount';priority='P2'}if(/価格改定/.test(title)){campaignType='price_change';priority='P2'}const p=priceFields(title,text);const regionScope=/東海3県|東海三県/.test(text)?'tokai':/愛知県限定|愛知限定/.test(text)?'aichi':/静岡県限定|静岡限定/.test(text)?'shizuoka':/店舗限定/.test(title)?'store_limited':/全国/.test(title)?'national':'unknown';return{campaignType,priority,price:p.price,priceText:p.priceText,allYouCanEat:/食べ放題/.test(title)||/食べ放題/.test(text),regionScope,limitedIngredients:INGREDIENTS.filter(x=>text.includes(x)).slice(0,8),weekdayCondition:/平日限定/.test(title)||/平日のみ/.test(text)?'平日限定':null}}
